### ISSUE TITLE
Having Multiple Prefixes.

### ISSUE THREAD

**Issue by Fallenthetaco** [Nedinator/djs-commands#1]
How can I make more than 1 prefix that is only server-wide. Like one prefix is this server and the other is from another server. Since the command handler is allowing only prefixes to be in an array meaning the bot will trigger in any prefix that is in the array.

**Comment by Hariix-Dev** [comment]
Look at my bot, I have already do that.

Set a prefix.
And in the on message event, just do CommandHandler.prefix = your server prefix;

**Comment by ghSP** [comment]
@Fallenthetaco you will need to do checks based on the server ID, and possibly have a database to remember it. Enmap might work well.

**Comment by Nedinator** [comment]
Prefixes replaced with slash commands
